# Jarvis
This notebook implements a chatbot from YouTube based on groq

In [10]:
from groq import Groq
import cv2
import pyperclip
from PIL import ImageGrab, Image
import google.generativeai as genai
import os
from faster_whisper import WhisperModel
import speech_recognition as sr
from openai import OpenAI
import pyaudio
import time
import re

wake_word = 'jarvis'

web_cam = cv2.VideoCapture(0)

sys_msg = (
    'You are a multi-modal AI voice assistant. Your user may or may not have attached a photo for context '
    '(either a screenshot or a webcam capture). Any photo has already been processed into a hihgly detailed '
    'text prompt that will be attached to their transcribed voice propmt. Generate the most usefil and '
    'factual response possible, carefully considering all previous generated test in your response before '
    'adding new tokens to the response. Do not expect or request images, just use the context if added. '
    'Use all of the context of this conversation so your response is relevant to the conversation. Make '
    'your responses clear and concise, avoiding any verbosity.'
)

convo = [{'role': 'system', 'content': sys_msg}]
genai.configure(api_key=os.environ.get("GOOGLE_API_KEY"))
openai_client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
generation_config = {
    'temperature': 0.7,
    'top_p': 1,
    'top_k': 1,
    'max_output_tokens': 2048
}
safety_settings = [
    {
        'category': 'HARM_CATEGORY_HARASSMENT',
        'threshold': 'BLOCK_NONE'
    },
    {
        'category': 'HARM_CATEGORY_HATE_SPEECH',
        'threshold': 'BLOCK_NONE'
    },
    {
        'category': 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        'threshold': 'BLOCK_NONE'
    },
    {
        'category': 'HARM_CATEGORY_DANGEROUS_CONTENT',
        'threshold': 'BLOCK_NONE'
    },
]
vision_model = genai.GenerativeModel('gemini-1.5-flash-latest',
                                    generation_config=generation_config,
                                    safety_settings=safety_settings)



groq_client = Groq()

def groq_prompt(prompt, img_context=None):
    if img_context:
        prompt = f'USER_PROMPT: {prompt}\n\n   IMAGE CONTEXT: {img_context}'
    convo.append({'role': 'user', 'content': prompt})
    chat_completion = groq_client.chat.completions.create(messages=convo, model="llama3-70b-8192")

    response = chat_completion.choices[0].message
    convo.append(response)
    return response.content

In [4]:
# test the prompt
prompt = input('USER: ')
response = groq_prompt(prompt)
print(response)

Hello! It's nice to meet you. I'm Jarvis, your AI voice assistant. I'm ready to help you with any questions or tasks you may have. What's on your mind today?

In [6]:


def function_call(prompt):
    sys_msg = (
        'You are an AI function calling model. You will determine which function from this list: '
        '["extract clipboard", "take screenshot", "capture webcam", "None"] should be called to gain the context '
        'for another AI to respond to the user. You are not responding to the user. You should only return one value from the list. '
        'If the user asks for help with something on their screen you should respond with "take screen shot". '
        'If the user asks for help on something in their environment or their physical appearance you should respond with "capture webcam". '
        'If the user asks for help with their clipboard content you should respond with "extract clipboard". '
        'If none of the previous options are appropriate respond with "None". Only respond woth one value from the list and do not provide any explanation.'
    ) 

    function_convo = [{'role': 'system', 'content': sys_msg},
                      {'role': 'user', 'content': prompt}]
    
    chat_completion = groq_client.chat.completions.create(messages=function_convo, model="mixtral-8x7b-32768")
    return chat_completion.choices[0].message.content

def take_screenshot():
    path = 'screenshot.jpg'
    screenshot = ImageGrab.grab()
    rgb_screenshot = screenshot.convert('RGB')
    rgb_screenshot.save(path, quality=15)


def web_cam_capture():
    if not web_cam.isOpened():
        print('Error: Camera did not open successfully')
        return
    
    path = 'webcam.jpg'
    ret, frame = web_cam.read()
    cv2.imwrite(path, frame)


def get_clipboard_text():
    clipboard_content = pyperclip.paste()
    if isinstance(clipboard_content, str):
        return clipboard_content
    else:
        print('Error: Clipboard content is not a string')
        return None

def vision_prompt(prompt, photo_path):
    img = Image.open(photo_path)
    prompt = (
        'You are the vision analysis AI that provides semantic meaning from images to provide context '
        'to send to another AI that will create a response to the user. Do not respond as the AI assistant '
        'to the user. Instead take the user prompt input and try to extract all meaning from the photo '
        'relevant to the user prompt. Then generate as much objective data about the image for the AI '
        'assistant who will respond to the user. \nUSER PROMPT: {prompt}'
    )
    response = vision_model.generate_content([prompt, img])
    return response.text

In [6]:
prompt = 'I want you to analyse the code I put on the clipboard.'
response = function_call(prompt)
print(response)
print(function_call("I am holding my dog up to the webcam. What is on his nose?"))

extract clipboard
capture webcam

In [7]:

web_cam_capture()
take_screenshot()
print(get_clipboard_text())

web_cam_capture()
take_screenshot()
print(get_clipboard_text())

In [12]:
def jarvis_prompt(prompt):
    call = function_call(prompt)
    call = call.lower()
    print(call)

    if 'take screenshot' in call:
        print('taking screenshot')
        take_screenshot()
        visual_context = vision_prompt(prompt, photo_path='screenshot.jpg')
        print(f'screenshot: {visual_context}')
    
    elif 'capture webcam' in call:
        print('capturing webcam')
        web_cam_capture()
        visual_context = vision_prompt(prompt, photo_path='webcam.jpg')
        print(f'webcam: {visual_context}')

    elif 'extract clipboard' in call:
        print('Copying clipboard text')
        paste = get_clipboard_text()
        prompt = f'{prompt}\n\n CLIPBOARD CONTENT: {paste}'
        print(f'clipboard: {paste}')
        visual_context = None
    else:
        visual_context = None

    response = groq_prompt(prompt=prompt, img_context=visual_context)
    print(response)
    speak(response)

def jarvis():
    finished = False
    while finished == False:
        visual_context=None
        prompt = input('USER: ')
        if 'bye' in prompt.lower():
            finished=True
            print('Bye')
            break
        jarvis_prompt(prompt.lower())

In [8]:
jarvis()

"take screenshot"
taking screenshot
screenshot: The image is of a computer screen displaying a code editor with several tabs open. The code editor is likely being used to develop a chatbot application. The code editor is displaying a function that takes a prompt, a visual context, and a photo path. The function then prints the prompt and the visual context. The function also prints a message indicating that a webcam is being captured. Finally, the function prints a message indicating that the clipboard is being copied. The user prompt is likely asking for information about the chatbot application, such as how it works or what it does. The chatbot application appears to be under development, as evidenced by the many files and folders that are open in the code editor. The chatbot application appears to be written in Python, as evidenced by the file extensions ".py" and ".ipynb" that are present in the code editor.
It seems you're developing a chatbot application, and I'm happy to help. Based on the code on your screen, I see that you're creating a function that takes a prompt, visual context, and a photo path as inputs. The function then prints out the prompt and visual context, and it also appears to be capturing webcam input and copying something to the clipboard.

From what I can gather, your chatbot is designed to work with multimodal inputs, processing both text and visual contexts. Am I correct?
Bye

In [13]:
def speak(text, voice = 'fable'):
    player_stream = pyaudio.PyAudio().open(format=pyaudio.paInt16, channels=1, rate=24000, output=True)
    stream_start = False

    with openai_client.audio.speech.with_streaming_response.create(
        model ='tts-1',
        voice=voice,
        response_format='pcm',
        input = text
    ) as response:
        silence_threshold = 0.01
        for chunk in response.iter_bytes(chunk_size=1024):
            if stream_start:
                player_stream.write(chunk)
            else:
                if max(chunk) > silence_threshold:
                    player_stream.write(chunk)
                    stream_start = True
    
num_cores = os.cpu_count()
print(f'Num Cores: {num_cores}')
whisper_size = 'base'
whisper_model = WhisperModel(
    whisper_size,
    device='cpu',
    compute_type='int8',
    cpu_threads=num_cores // 2,
    num_workers=num_cores // 2
)

def wav_to_text(audio_path):
    segments, _ = whisper_model.transcribe(audio_path)
    text = ''.join([segment.text for segment in segments])
    return text
    
r = sr.Recognizer()
source = sr.Microphone()

def callback(recognizer, audio):
    prompt_audio_path = 'prompt.wav'
    with open(prompt_audio_path, 'wb') as f:
        f.write(audio.get_wav_data())

    prompt_text = wav_to_text(prompt_audio_path)
    clean_prompt = extract_prompt(prompt_text, wake_word)

    if clean_prompt:
        jarvis_prompt(clean_prompt)

def start_listening():
    with source as s:
        r.adjust_for_ambient_noise(s, duration=2)

    print(f'\nSay {wake_word} followed with your prompt.\n')
    r.listen_in_background(source, callback)

    while True:
        time.sleep(0.5)

def extract_prompt(transcribed_text, wake_word):
    pattern = rf'\b{re.escape(wake_word)}[\s,.?!]*([A-Za-z0-9].*)'
    match = re.search(pattern, transcribed_text, re.IGNORECASE)

    if match:
        prompt = match.group(1).strip()
        return prompt

    return None

Num Cores: 6

vocabulary.txt:   0%|          | 0.00/460k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.31k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.20M [00:00<?, ?B/s]

model.bin:   0%|          | 0.00/145M [00:00<?, ?B/s]

In [4]:
import time

voices = ['shimmer', 'nova', 'onyx', 'fable', 'echo', 'alloy']

for name in voices:
    hello = f'Hello World. I am {name}.'
    speak(hello, name)
    time.sleep(1)

In [14]:
start_listening()

Say jarvis followed with your promt.

"take screenshot"
taking screenshot
screenshot: {prompt}

The image is a screenshot of a computer program written in Python. The code is for a chatbot called Jarvis. The code is in a Jupyter Notebook. The notebook is open in a program called VS Code. The code is loading a model called "llama3-70b-8192". The code is also loading a package called "portaudio".  The code is running on a computer called "johns-imac". The code is being run by a user named "Scalzi". The user has a project folder called "Jarvis" and the code is in a file called "ExploreJarvisPrompts.ipynb". The code is also in a file called "jarvis.ipynb".
Based on the screenshot, I see a Jupyter Notebook open in VS Code, running on a computer called "johns-imac" by user "Scalzi". The code appears to be for a chatbot called Jarvis, specifically loading a model called "llama3-70b-8192" and package "portaudio". The notebook is part of a project folder called "Jarvis" and contains files "ExploreJarvisPrompts.ipynb" and "jarvis.ipynb".
extract clipboard
Copying clipboard text
clipboard:         call = function_call(prompt)
        call = call.lower()
        print(call)

        if 'take screenshot' in call:
            print('taking screenshot')
            take_screenshot()
            visual_context = vision_prompt(prompt, photo_path='screenshot.jpg')
            print(f'screenshot: {visual_context}')

        elif 'capture webcam' in call:
            print('capturing webcam')
            web_cam_capture()
            visual_context = vision_prompt(prompt, photo_path='webcam.jpg')
            print(f'webcam: {visual_context}')

        elif 'extract clipboard' in call:
            print('Copying clipboard text')
            paste = get_clipboard_text()
            prompt = f'{prompt}\n\n CLIPBOARD CONTENT: {paste}'
            print(f'clipboard: {paste}')
            visual_context = None

        response = groq_prompt(prompt=prompt, img_context=visual_context)
        print(response)
        speak(response)
Based on the code, it appears that the voice used will be generated by the `groq_prompt` function, which takes the processed prompt and visual context as input, and returns a response that is then spoken using the `speak` function.

KeyboardInterrupt:

In [ ]:
local_llm = 'llama3-70b-8192'
chat_llm = ChatGroq(temperature=0, model_name=local_llm)
output_parser = JsonOutputParser()

chain = chat_llm | RunnableLambda(FilterOutExtraToJSON) | output_parser | RunnableLambda(ExtractKey('function'))

run_test(f'Test 12: JSON function prompt with None as a choice using {local_llm} on Groq', 'FunctionCallPromptJSON3.txt', chain, "TestFunctionsWithNone.tsv")

Test 12: JSON function prompt with None as a choice using llama3-70b-8192 on Groq

Labels: ['capture webcam', 'none', 'read clipboard', 'search web', 'take screenshot']
                 capture webcam  none  read clipboard  search web  \
capture webcam               17     0               0           0
none                          0     1               0           2
read clipboard                0     0              14           0
search web                    1     0               0          15
take screenshot               0     0               1           0

                 take screenshot
capture webcam                 2
none                           0
read clipboard                 0
search web                     0
take screenshot               15
Failures:
Is there anything interesting on the document I just opened? Expected: take screenshot      Result: read clipboard
Can you see if my desktop background is appropriate?         Expected: capture webcam       Result: take screenshot
Can you see if my laptop is plugged in?                      Expected: capture webcam       Result: take screenshot
Can you help me solve this math problem?                     Expected: none                 Result: search web
How do I change the tire on my car?                          Expected: search web           Result: capture webcam
Can you tell me a joke?                                      Expected: none                 Result: search web
Accuracy: 91.18%

,capture webcam,none,read clipboard,search web,take screenshot
capture webcam,17,0,0,0,2
none,0,1,0,2,0
read clipboard,0,0,14,0,0
search web,1,0,0,15,0
take screenshot,0,0,1,0,15

In [ ]:
local_llm = 'llama3-70b-8192'
chat_llm = ChatGroq(temperature=0, model_name=local_llm)
output_parser = JsonOutputParser()

chain = chat_llm | RunnableLambda(FilterOutExtraToJSON) | output_parser | RunnableLambda(ExtractKey('function'))

run_test(f'Test 12: JSON function prompt with None as a choice using {local_llm} on Groq', 'FunctionCallPromptJSON3.txt', chain, "TestFunctionsWithNone.tsv")

Test 12: JSON function prompt with None as a choice using llama3-70b-8192 on Groq

Labels: ['capture webcam', 'none', 'read clipboard', 'search web', 'take screenshot']
                 capture webcam  none  read clipboard  search web  \
capture webcam               17     0               0           0
none                          0     1               0           2
read clipboard                0     0              14           0
search web                    1     0               0          15
take screenshot               0     0               1           0

                 take screenshot
capture webcam                 2
none                           0
read clipboard                 0
search web                     0
take screenshot               15
Failures:
Is there anything interesting on the document I just opened? Expected: take screenshot      Result: read clipboard
Can you see if my desktop background is appropriate?         Expected: capture webcam       Result: take screenshot
Can you see if my laptop is plugged in?                      Expected: capture webcam       Result: take screenshot
Can you help me solve this math problem?                     Expected: none                 Result: search web
How do I change the tire on my car?                          Expected: search web           Result: capture webcam
Can you tell me a joke?                                      Expected: none                 Result: search web
Accuracy: 91.18%

,capture webcam,none,read clipboard,search web,take screenshot
capture webcam,17,0,0,0,2
none,0,1,0,2,0
read clipboard,0,0,14,0,0
search web,1,0,0,15,0
take screenshot,0,0,1,0,15

In [ ]:
local_llm = 'llama3-70b-8192'
chat_llm = ChatGroq(temperature=0, model_name=local_llm)
output_parser = JsonOutputParser()

chain = chat_llm | RunnableLambda(FilterOutExtraToJSON) | output_parser | RunnableLambda(ExtractKey('function'))

run_test(f'Test 12: JSON function prompt with None as a choice using {local_llm} on Groq', 'FunctionCallPromptJSON3.txt', chain, "TestFunctionsWithNone.tsv")

Test 12: JSON function prompt with None as a choice using llama3-70b-8192 on Groq

Labels: ['capture webcam', 'none', 'read clipboard', 'search web', 'take screenshot']
                 capture webcam  none  read clipboard  search web  \
capture webcam               17     0               0           0
none                          0     1               0           2
read clipboard                0     0              14           0
search web                    1     0               0          15
take screenshot               0     0               1           0

                 take screenshot
capture webcam                 2
none                           0
read clipboard                 0
search web                     0
take screenshot               15
Failures:
Is there anything interesting on the document I just opened? Expected: take screenshot      Result: read clipboard
Can you see if my desktop background is appropriate?         Expected: capture webcam       Result: take screenshot
Can you see if my laptop is plugged in?                      Expected: capture webcam       Result: take screenshot
Can you help me solve this math problem?                     Expected: none                 Result: search web
How do I change the tire on my car?                          Expected: search web           Result: capture webcam
Can you tell me a joke?                                      Expected: none                 Result: search web
Accuracy: 91.18%

,capture webcam,none,read clipboard,search web,take screenshot
capture webcam,17,0,0,0,2
none,0,1,0,2,0
read clipboard,0,0,14,0,0
search web,1,0,0,15,0
take screenshot,0,0,1,0,15